import { app, BrowserWindow, ipcMain, dialog, protocol, net, nativeImage } from 'electron'
import { join } from 'path'
import { readFile, writeFile, mkdir } from 'fs/promises'
import { existsSync } from 'fs'
import { pathToFileURL } from 'url'
import { buildMenu } from './menu'
import { readFile as fsReadFile, readdirSync } from 'fs'
import { promisify } from 'util'
import { readSettings, writeSettings, DEFAULT_ICONS_DIR } from './settingsStore'

const readFileAsync = promisify(fsReadFile)

app.setName('ArchDiagram')

// Set dock icon (works in dev; packaged builds use electron-builder icon config)
const iconPath = join(app.getAppPath(), 'resources/icon.icns')
if (existsSync(iconPath) && app.dock) {
  app.dock.setIcon(nativeImage.createFromPath(iconPath))
}

const isDev = !app.isPackaged

function createWindow(): BrowserWindow {
  const win = new BrowserWindow({
    width: 1440,
    height: 900,
    titleBarStyle: 'hiddenInset',
    webPreferences: {
      preload: join(__dirname, '../preload/preload.js'),
      contextIsolation: true,
      sandbox: false,
    },
  })

  if (isDev) {
    win.loadURL('http://localhost:5173')
    win.webContents.openDevTools()
  } else {
    win.loadFile(join(__dirname, '../renderer/index.html'))
  }

  return win
}

// Register archdoc:// protocol for secure local asset loading
app.whenReady().then(() => {
  protocol.handle('archdoc', (request) => {
    const url = request.url.replace('archdoc://', '')
    const filePath = join(app.getAppPath(), url)
    return net.fetch(pathToFileURL(filePath).toString())
  })

  const win = createWindow()
  buildMenu(win)

  // Ensure default custom icons directory exists
  const defaultCustomIconsDir = join(app.getPath('userData'), 'custom-icons')
  if (!existsSync(defaultCustomIconsDir)) {
    mkdir(defaultCustomIconsDir, { recursive: true }).catch(console.error)
  }

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      const newWin = createWindow()
      buildMenu(newWin)
    }
  })
})

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit()
})

// IPC: Open file
ipcMain.handle('file:open', async () => {
  const win = BrowserWindow.getFocusedWindow()
  if (!win) return null

  const { canceled, filePaths } = await dialog.showOpenDialog(win, {
    filters: [{ name: 'Architecture Diagrams', extensions: ['archdoc.json', 'json'] }],
    properties: ['openFile'],
  })

  if (canceled || filePaths.length === 0) return null

  const content = await readFile(filePaths[0], 'utf-8')
  return { filePath: filePaths[0], content: JSON.parse(content) }
})

// IPC: Save file
ipcMain.handle('file:save', async (_event, { content, filePath }: { content: unknown; filePath?: string }) => {
  const win = BrowserWindow.getFocusedWindow()
  if (!win) return null

  let savePath = filePath
  if (!savePath) {
    const { canceled, filePath: chosen } = await dialog.showSaveDialog(win, {
      defaultPath: 'diagram.archdoc.json',
      filters: [{ name: 'Architecture Diagrams', extensions: ['archdoc.json', 'json'] }],
    })
    if (canceled || !chosen) return null
    savePath = chosen
  }

  await writeFile(savePath, JSON.stringify(content, null, 2), 'utf-8')
  return savePath
})

// IPC: Export PNG (data URL from renderer → write file)
ipcMain.handle('export:png', async (_event, { dataUrl, outputPath }: { dataUrl: string; outputPath: string }) => {
  const base64 = dataUrl.replace(/^data:image\/png;base64,/, '')
  await writeFile(outputPath, Buffer.from(base64, 'base64'))
})

// IPC: Write raw base64 bytes (used for PDF generated by jsPDF in renderer)
ipcMain.handle('export:raw', async (_event, { base64, outputPath }: { base64: string; outputPath: string }) => {
  await writeFile(outputPath, Buffer.from(base64, 'base64'))
})

// IPC: Get save dialog path for PNG
ipcMain.handle('dialog:save-png', async () => {
  const win = BrowserWindow.getFocusedWindow()
  if (!win) return null

  const { canceled, filePath } = await dialog.showSaveDialog(win, {
    defaultPath: 'diagram.png',
    filters: [{ name: 'PNG Image', extensions: ['png'] }],
  })
  return canceled ? null : filePath
})

// IPC: Get save dialog path for PDF
ipcMain.handle('dialog:save-pdf', async () => {
  const win = BrowserWindow.getFocusedWindow()
  if (!win) return null

  const { canceled, filePath } = await dialog.showSaveDialog(win, {
    defaultPath: 'diagram.pdf',
    filters: [{ name: 'PDF Document', extensions: ['pdf'] }],
  })
  return canceled ? null : filePath
})

// IPC: Load custom icons — scans directory for SVGs, auto-generates manifest (no manifest.json needed)
ipcMain.handle('icons:load-custom', async () => {
  const settings = await readSettings()
  const customIconsDir = settings.customIconsDir ?? DEFAULT_ICONS_DIR

  if (!existsSync(customIconsDir)) return null

  try {
    const allFiles = readdirSync(customIconsDir)
    const svgFiles = allFiles.filter((f) => f.toLowerCase().endsWith('.svg'))
    if (svgFiles.length === 0) return null

    // Group icons by service (derived from filename: Res_<Service>_<Resource>_48.svg)
    const categoryMap = new Map<string, Array<{ id: string; name: string; fileName: string }>>()

    for (const fileName of svgFiles) {
      const base = fileName.replace(/\.svg$/i, '')
      // Strip leading "Res_" and trailing "_48" (or similar size suffix)
      const stripped = base.replace(/^Res_/, '').replace(/_\d+$/, '')
      const underscoreIdx = stripped.indexOf('_')
      let service: string
      let resource: string
      if (underscoreIdx === -1) {
        service = 'Custom'
        resource = stripped
      } else {
        service = stripped.slice(0, underscoreIdx).replace(/-/g, ' ')
        resource = stripped.slice(underscoreIdx + 1).replace(/-/g, ' ')
      }

      const id = `custom_${base.toLowerCase().replace(/[^a-z0-9]+/g, '_')}`
      if (!categoryMap.has(service)) categoryMap.set(service, [])
      categoryMap.get(service)!.push({ id, name: resource, fileName })
    }

    // Build manifest
    const categories = Array.from(categoryMap.entries()).map(([name, icons]) => ({
      name,
      icons: icons.map(({ id, name: iconName, fileName }) => ({
        id,
        name: iconName,
        provider: 'custom' as const,
        category: name,
        tags: iconName.toLowerCase().split(' '),
        svgPath: fileName,
      })),
    }))
    const manifest = { provider: 'custom' as const, version: '1.0', categories }

    // Load SVG contents
    const svgs: Record<string, string> = {}
    for (const cat of categories) {
      for (const icon of cat.icons) {
        const svgPath = join(customIconsDir, icon.svgPath)
        svgs[icon.id] = await readFileAsync(svgPath, 'utf-8')
      }
    }

    return { manifest, svgs }
  } catch (err) {
    console.error('icons:load-custom error', err)
    return null
  }
})

// IPC: Get current settings
ipcMain.handle('settings:get', async () => {
  return readSettings()
})

// IPC: Update settings
ipcMain.handle('settings:set', async (_event, partial: Record<string, unknown>) => {
  return writeSettings(partial)
})

// IPC: Open native folder picker for icon directory
ipcMain.handle('settings:pick-icons-dir', async () => {
  const win = BrowserWindow.getFocusedWindow()
  if (!win) return null

  const { canceled, filePaths } = await dialog.showOpenDialog(win, {
    title: 'Select Custom Icons Directory',
    properties: ['openDirectory'],
  })
  return canceled || filePaths.length === 0 ? null : filePaths[0]
})
